### ISSUE TITLE
esx_subway facture 

### ISSUE THREAD

**Issue by AftRolePlay** [Fellow25/esx_subway#1]
bonjour possible que vous rajoutiez le system de facture style dans le f6 seulement le Menu Facture merci a vous très bon job au passage

**Comment by SUP2Ak** [comment]
On fait pas des issues pour des ajouts, mais pour des bugs passe sur son discord pour cela.

**Comment by AftRolePlay** [comment]
ah ok désole alors je vais voir sur le discord alors merci a vous pour votre réponse rapide
